# Generated by Django 5.1.4 on 2025-02-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_report_status_alter_report_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved_photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/resolved/'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
